### ISSUE TITLE
Need more docs and example to guide new users

### ISSUE THREAD

**Issue by lingtaolf** [danalite/autool#1]
I've downloaded this app on my mbp. But don't know how to use it at all. I think it's better add more docs and examples to tell new users how to use it.

**Comment by lifesign** [comment]
+1

**Comment by vrteee** [comment]
sorry for the late reply. I just updated the README to demonstrate how to install the plugins. All the plugins I demonstrated before are available in this repo: https://github.com/danalites/apps/tree/master/danalites

you can install it by following the instructions here: https://github.com/danalites/apps/tree/master/danalites

My apology for the missing documents, as I am recently working on revamping AuTool. Will work on the documents soon and put a video link on the README for quick tutorial.

**Comment by december-mountain** [comment]
> 这么晚才回复很抱歉。我刚刚更新了自述文件以演示如何安装插件。我之前演示的所有插件都可以在这个 repo 中找到：https://github.com/danalites/apps/tree/master/danalites
> 
> 您可以按照此处的说明进行安装： https: [//github.com/danalites/apps/tree/master/danalites](https://github.com/danalites/apps/tree/master/danalites)
> 
> 对于丢失的文件，我深表歉意，因为我最近正在改造 AuTool。将很快处理文档，并在 README 上放一个视频链接以获取快速教程。

您好，您提供的两个链接都显示404了。

**Comment by vrteee** [comment]
@december-mountain 你好，新的网站迁移到 https://autool.site/zh
不过还在完善中，很多例子还没有补充好
