### ISSUE TITLE
导入了APP，但是运行后没反应，debug如下

### ISSUE THREAD

**Issue by aLIEz-xue** [danalite/autool#2]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/59567929/226096480-99a59c35-a442-407d-acba-f9a66d99da1e.png">
这个文件是需要自己创建吗，还是需要给什么权限，辅助权限已经给过了

**Comment by vrteee** [comment]
这是一个bug，因为/Users/xxx/Library/Application Support/lib auto/logs 文件夹没有生成。我会在0.02版本修复
一个临时的解决办法是，手动生成这个文件夹，然后app的log就可以成功打印了

**Comment by vrteee** [comment]
Fixed in 0.0.14. 
v0.1之后会加一个社区应用的选项，直接下载，不用再手动导入app
