### ISSUE TITLE
win10显示错误

### ISSUE THREAD

**Issue by Jamie-Wan** [danalite/autool#4]
![image](https://user-images.githubusercontent.com/65280479/229686772-83377818-2eb2-4090-9675-141b317fed57.png)
打开后自动跳出，无法关闭

**Comment by hecmay** [comment]
v0.02?

**Comment by vrteee** [comment]
v0.02?

**Comment by Jamie-Wan** [comment]
> v0.02?

是的，最新版

**Comment by vrteee** [comment]
> > v0.02?
> 
> 是的，最新版

打包落了一个dependency，正在修了

**Comment by Jamie-Wan** [comment]
0.04，还是这个问题
![image](https://user-images.githubusercontent.com/65280479/230536723-5fc17a3d-f41f-4631-856f-8dc2342c4337.png)

**Comment by vrteee** [comment]
REF: https://stackoverflow.com/questions/75668307/error-in-native-callback-using-ffi-napi-in-electron-and-electron-builder
```bash
$ electron-builder install-app-deps
  • electron-builder  version=23.6.0
  • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, iconv@2.3.5, ref-napi@3.0.3, uiohook-napi@1.5.0 platform=win32 arch=x64
  • rebuilding native dependency  name=ffi-napi version=4.0.3
  • rebuilding native dependency  name=iconv version=2.3.5
  • rebuilding native dependency  name=ref-napi version=3.0.3
  • rebuilding native dependency  name=uiohook-napi version=1.5.0
```

**Comment by vrteee** [comment]
还没修好
```bash
Error: Cannot find module 'ffi-napi'
```

**Comment by vrteee** [comment]
应该还是打包的问题，我本地打包的就可以用：https://github.com/danalite/autool/releases/download/v0.0.5/AuTool-0.0.5-win32-portable.zip

修好了@你

**Comment by vrteee** [comment]
@Jamie-Wan Fixed in release 14
